name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mfinelli/setup-shfmt@v3
      - run: shellcheck wireguard-install.sh
      - run: shfmt -d wireguard-install.sh
      - run: bash -n wireguard-install.sh
